### ISSUE TITLE
Gestione categorie, errori rilevati

### ISSUE THREAD

**Issue by vormix** [vormix/PHP-Ecommerce#15]
Errori correlati al commit 290ef26ad24132f1a7bc29cc03cc2ae06a3a6327

**Organizzazione del progetto:**

1) il file sql deve essere posizionato nella sottocartella **/php-ecommerce/sql/** e deve avere naming convention **yyyymmddhhmm.sql** altrimenti non viene gestita dal sistema automatico di aggiornamento
2) non utilizzare il nome del database negli script altrimenti non funziona se ho messo un nome differete al db

**Bug Rilevati**

1) Cliccando su "aggiungi categoria" ottengo errore e non posso testare funzionamento della form (vedi immagine)
![AggiungiCategoria](https://user-images.githubusercontent.com/23016800/77223249-00552f00-6b5b-11ea-84c7-0a6d5dfc0faf.jpg)

2) Se aggiungo manualmente una categoria da database, aprendo al pagina "Elenco categorie" ottengo errore (vedi immagine)
![ElencoCategorie](https://user-images.githubusercontent.com/23016800/77223266-3d212600-6b5b-11ea-8dea-a027e0a13389.jpg)

**Comment by GdmDev** [comment]
Attività chiusa con commit: 956c56de0feb146e58147f88206d519da401614e
