### ISSUE TITLE
Offerta visibile su sconti scaduti

### ISSUE THREAD

**Issue by GdmDev** [vormix/PHP-Ecommerce#2]
Pagina: lista prodotti:

si vede la label dell'offerta anche se effettivamente la data di fine sconto è trascorsa

**Comment by GdmDev** [comment]
risolto ora:
1)metti % sconto e lasci in bianco le date (sconto persistente nel tempo)
2) metti % sconto e inserisci solo data di inizio (sconto comincia a una data e diventa persiste nel tempo)
3) metti % sconto e inserisci solo la data di fine (sconto parte da subito e rimane fino a data fine)
4)non inserisci % sconto non prende proprio in considerazione perchè le date assumono  1901- entrambe

**Comment by vormix** [comment]
L'errore si presenta ancora

**Comment by vormix** [comment]
Il problema è risolto
