### ISSUE TITLE
NO UPLOAD IMG SU PRODOTTI

### ISSUE THREAD

**Issue by GdmDev** [vormix/PHP-Ecommerce#4]
Se i prodotti non hanno immagine in creazione non riesce a fare upload
non crea nulla proprio strano lo faceva....non ho toccato nulla

**Comment by vormix** [comment]
Non è strano,  è un errore che mi aspettavo... il motivo è che in fase di salvataggio, la procedura usa il productId per determinare la directory e, se il prodotto è nuovo questo dato non ce l'ha... probabilmente creerà un record con productId zero, ma in tal caso non lo vedi a interfaccia, dobbiamo gestirlo

**Comment by vormix** [comment]
bug corretto appoggiando le immagini in una cartella temporanea se ancora non esiste l'id del prodotto
