### ISSUE TITLE
Amministrazione: paginazione delle tabelle e ricerca

### ISSUE THREAD

**Issue by vormix** [vormix/PHP-Ecommerce#40]
Paginare e aggiungere un campo di ricerca alle seguenti tabelle:

1) Lista prodotti
2) Lista utenti
3) Lista categorie

**Comment by GdmDev** [comment]
non ho capito cosa significa poi queste issues sono tutte aperte?

**Comment by vormix** [comment]
> non ho capito cosa significa poi queste issues sono tutte aperte?

Ho gestito i task da fare come issues con la label "enhancement" (celeste chiaro), mentre i malfunzionamenti con la label "bug" (rosso)
Di seguito un un esempio 
![Screenshot_20200323-074554_Chrome~2](https://user-images.githubusercontent.com/23016800/77289804-fb1eee00-6cda-11ea-895c-e6c3fa581dc2.jpg)

**Comment by vormix** [comment]
Fatto
commit 9d59e8e9a6d08965d8a4c1ddfd7e91fb285bb311
