### ISSUE TITLE
Gestione Spedizione nel Carrello con Modifica in runtime dei Totali

### ISSUE THREAD

**Issue by GdmDev** [vormix/PHP-Ecommerce#43]
Abbiamo gestito tutto il flusso del carrello che porta alla sua configurazione per il pagamento 
quindi prodotti quantità e prezzi subtotali e prezzo totale del carrello stesso in base alla spedizione scelta che anch'essa viene conteggiata nel totale
 Commit:
Vormix:  6eb85b43de5070c991ccdc0ee190cbe25c093809

**Comment by GdmDev** [comment]
6eb85b43de5070c991ccdc0ee190cbe25c093809

**Comment by vormix** [comment]
Fixato bug in visualizzazione, Commit 5546e6f3a46e8c31a79dc520d33740d5314fdfd5
