### ISSUE TITLE
Cancellazione ordine 

### ISSUE THREAD

**Issue by GdmDev** [vormix/PHP-Ecommerce#5]
Se uno non ha pagato o se non completa l'ordine l'admin e l'utente stesso dell ordine in questione devono poterlo cancellare anche se inviato

**Comment by vormix** [comment]
questo non è un bug, ma una proposta di miglioramento (una funzionalità da implementare), quindi non va messa qui, bensì nella sezione "Projects".

Chiudo la segnalazione e sposto il contenuto nella sezione giusta.
